//! Component variant of the detector. Mirrors `crates/detector/build.rs`
//! but reads the WAT probe fixtures out of the sibling detector crate so
//! there's exactly one on-disk source of probes.

use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Deserialize)]
struct Registry {
    feature: Vec<Feature>,
}

#[derive(Deserialize)]
struct Feature {
    name: String,
    bit: u32,
    probe: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("expected crate to live at <workspace>/crates/<name>");
    let features_toml = workspace_root.join("features.toml");
    // Reuse the WAT fixtures that live with the core detector crate so
    // the two builds can never drift.
    let probes_dir = workspace_root.join("crates/detector/src/probes");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", features_toml.display());
    println!("cargo:rerun-if-changed={}", probes_dir.display());

    let toml_src = fs::read_to_string(&features_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", features_toml.display()));
    let mut registry: Registry =
        toml::from_str(&toml_src).unwrap_or_else(|e| panic!("parse features.toml: {e}"));
    registry.feature.sort_by_key(|f| f.bit);

    for (i, feature) in registry.feature.iter().enumerate() {
        assert_eq!(
            feature.bit as usize, i,
            "feature bit indices must be contiguous and start at 0 (got {} at position {i})",
            feature.bit
        );
    }

    let mut code = String::new();
    code.push_str("// Generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub const FEATURE_COUNT: usize = {};\n\n",
        registry.feature.len()
    ));
    code.push_str(
        "pub struct Probe {\n    pub name: &'static str,\n    pub bytes: &'static [u8],\n}\n\n",
    );
    code.push_str("pub static PROBES: [Probe; FEATURE_COUNT] = [\n");

    for feature in &registry.feature {
        let wat_path = probes_dir.join(format!("{}.wat", feature.probe));
        let wat_src = fs::read_to_string(&wat_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", wat_path.display()));
        let wasm_bytes = wat::parse_str(&wat_src)
            .unwrap_or_else(|e| panic!("compile {}: {e}", wat_path.display()));
        let wasm_out = out_dir.join(format!("{}.wasm", feature.probe));
        fs::write(&wasm_out, &wasm_bytes).unwrap();
        code.push_str(&format!(
            "    Probe {{ name: {:?}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{}.wasm\")) }},\n",
            feature.name, feature.probe
        ));
    }

    code.push_str("];\n");
    fs::write(out_dir.join("probes.rs"), code).unwrap();
}
