//! Merges the two build-time tables (core-wasm probes + browser
//! catalog) into a single generated Rust file consumed by `src/lib.rs`.
//! Read straight from the workspace-root sources so this crate never
//! carries its own copy of `features.toml` / `browser-features.toml` /
//! `browser-subfeatures.toml` — a change in either lands in both the
//! sibling detector crates and here without a drift window.

use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Deserialize)]
struct FeatureRegistry {
    feature: Vec<Feature>,
}

#[derive(Deserialize)]
struct Feature {
    name: String,
    bit: u32,
    probe: String,
}

#[derive(Deserialize)]
struct BrowserCatalog {
    #[serde(default)]
    browser: Vec<BrowserEntry>,
}

#[derive(Deserialize)]
struct BrowserEntry {
    package: String,
}

#[derive(Deserialize)]
struct SubfeatureCatalog {
    #[serde(default, rename = "subfeature-set")]
    sets: Vec<SubfeatureSet>,
}

#[derive(Deserialize)]
struct SubfeatureSet {
    package: String,
    names: Vec<String>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("expected crate to live at <workspace>/crates/<name>");
    let features_toml = workspace_root.join("features.toml");
    let probes_dir = workspace_root.join("crates/detector/src/probes");
    let browser_toml = workspace_root.join("browser-features.toml");
    let subs_toml = workspace_root.join("browser-subfeatures.toml");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", features_toml.display());
    println!("cargo:rerun-if-changed={}", probes_dir.display());
    println!("cargo:rerun-if-changed={}", browser_toml.display());
    println!("cargo:rerun-if-changed={}", subs_toml.display());

    let mut code = String::new();
    code.push_str("// Generated by build.rs — do not edit.\n\n");

    // --- Core feature registry ---------------------------------------

    let toml_src = fs::read_to_string(&features_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", features_toml.display()));
    let mut registry: FeatureRegistry =
        toml::from_str(&toml_src).unwrap_or_else(|e| panic!("parse features.toml: {e}"));
    registry.feature.sort_by_key(|f| f.bit);
    for (i, feature) in registry.feature.iter().enumerate() {
        assert_eq!(
            feature.bit as usize, i,
            "feature bit indices must be contiguous and start at 0 (got {} at position {i})",
            feature.bit
        );
    }
    code.push_str(&format!(
        "pub const FEATURE_COUNT: usize = {};\n\n",
        registry.feature.len()
    ));
    code.push_str(
        "pub struct CoreProbe {\n    pub name: &'static str,\n    pub bytes: &'static [u8],\n}\n\n",
    );
    code.push_str("pub static CORE_PROBES: [CoreProbe; FEATURE_COUNT] = [\n");
    for feature in &registry.feature {
        let wat_path = probes_dir.join(format!("{}.wat", feature.probe));
        let wat_src = fs::read_to_string(&wat_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", wat_path.display()));
        let wasm_bytes = wat::parse_str(&wat_src)
            .unwrap_or_else(|e| panic!("compile {}: {e}", wat_path.display()));
        let wasm_out = out_dir.join(format!("core_{}.wasm", feature.probe));
        fs::write(&wasm_out, &wasm_bytes).unwrap();
        code.push_str(&format!(
            "    CoreProbe {{ name: {:?}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/core_{}.wasm\")) }},\n",
            feature.name, feature.probe
        ));
    }
    code.push_str("];\n\n");

    // --- Browser catalog ---------------------------------------------

    let browser_src = fs::read_to_string(&browser_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", browser_toml.display()));
    let catalog: BrowserCatalog =
        toml::from_str(&browser_src).unwrap_or_else(|e| panic!("parse browser-features.toml: {e}"));
    let subs_src = fs::read_to_string(&subs_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", subs_toml.display()));
    let subs: SubfeatureCatalog =
        toml::from_str(&subs_src).unwrap_or_else(|e| panic!("parse browser-subfeatures.toml: {e}"));

    for set in &subs.sets {
        if !catalog.browser.iter().any(|e| e.package == set.package) {
            panic!(
                "browser-subfeatures.toml references {} which is not in \
                 browser-features.toml — either the catalog was regenerated \
                 after the package was renamed/removed, or the subfeature \
                 entry needs updating",
                set.package
            );
        }
    }

    code.push_str(&format!(
        "pub const BROWSER_PACKAGE_COUNT: usize = {};\n\n",
        catalog.browser.len()
    ));
    code.push_str(
        "pub struct BrowserPackage {\n    \
             pub name: &'static str,\n    \
             pub subfeatures: &'static [&'static str],\n\
         }\n\n",
    );

    for set in &subs.sets {
        let ident = sanitise_ident(&set.package);
        code.push_str(&format!("static SUBFEATURES_{ident}: &[&str] = &["));
        for name in &set.names {
            code.push_str(&format!("{name:?}, "));
        }
        code.push_str("];\n");
    }
    code.push('\n');

    code.push_str("pub static BROWSER_PACKAGES: [BrowserPackage; BROWSER_PACKAGE_COUNT] = [\n");
    for entry in &catalog.browser {
        let subs_ref = match subs.sets.iter().find(|s| s.package == entry.package) {
            Some(s) => format!("SUBFEATURES_{}", sanitise_ident(&s.package)),
            None => "&[]".to_string(),
        };
        code.push_str(&format!(
            "    BrowserPackage {{ name: {:?}, subfeatures: {subs_ref} }},\n",
            entry.package
        ));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("tables.rs"), code).unwrap();
}

fn sanitise_ident(package: &str) -> String {
    package
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_uppercase()
}
