// Assemble the browser-capability catalog into a Rust static consumed by
// `src/lib.rs`. The two input files are the workspace-root manifests
// documented in the top-level `browser-features.toml` header:
//
//   browser-features.toml     — auto-generated list of `[[browser]]`
//                                capability packages. Source of truth for
//                                iteration order (alphabetical); one entry
//                                per browser:* WIT package.
//   browser-subfeatures.toml  — hand-authored subfeature taxonomies. Only
//                                packages whose WIT docstrings enumerate
//                                progressive layers (browser:webgpu today)
//                                appear here.
//
// The two are kept separate on disk because their lifecycle differs:
// `browser-features.toml` regenerates on every `scripts/gen-browser-catalog.mjs`
// run and would clobber any inline subfeature edits, whereas subfeature slugs
// are hand-authored WIT-taxonomy decisions. Merging them here (rather than at
// runtime) means the wasm component ships with a single flat catalog and no
// TOML parser bloat.

use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Deserialize)]
struct Catalog {
    #[serde(default)]
    browser: Vec<CatalogEntry>,
}

#[derive(Deserialize)]
struct CatalogEntry {
    package: String,
}

#[derive(Deserialize)]
struct SubfeatureCatalog {
    #[serde(default, rename = "subfeature-set")]
    sets: Vec<SubfeatureSet>,
}

#[derive(Deserialize)]
struct SubfeatureSet {
    package: String,
    names: Vec<String>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("expected crate to live at <workspace>/crates/<name>");
    let catalog_path = workspace_root.join("browser-features.toml");
    let subs_path = workspace_root.join("browser-subfeatures.toml");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", catalog_path.display());
    println!("cargo:rerun-if-changed={}", subs_path.display());

    let catalog_src = fs::read_to_string(&catalog_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", catalog_path.display()));
    let catalog: Catalog = toml::from_str(&catalog_src)
        .unwrap_or_else(|e| panic!("parse browser-features.toml: {e}"));

    let subs_src = fs::read_to_string(&subs_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", subs_path.display()));
    let subs: SubfeatureCatalog = toml::from_str(&subs_src)
        .unwrap_or_else(|e| panic!("parse browser-subfeatures.toml: {e}"));

    // Cross-check: every `[[subfeature-set]]` package must exist in
    // `browser-features.toml`, otherwise the subfeature entry is dead
    // weight and probably signals a stale rename. Fail loudly.
    for set in &subs.sets {
        if !catalog.browser.iter().any(|e| e.package == set.package) {
            panic!(
                "browser-subfeatures.toml references {} which is not in \
                 browser-features.toml — either the catalog was regenerated \
                 after the package was renamed/removed, or the subfeature \
                 entry needs updating",
                set.package
            );
        }
    }

    let mut code = String::new();
    code.push_str("// Generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub const PACKAGE_COUNT: usize = {};\n\n",
        catalog.browser.len()
    ));
    code.push_str(
        "pub struct BrowserPackage {\n    \
             pub name: &'static str,\n    \
             pub subfeatures: &'static [&'static str],\n\
         }\n\n",
    );

    // Emit one static slice per package that has subfeatures, so the
    // main `PACKAGES` table can point at them. Package names may
    // contain `:`, `@`, `.`, and `-`; sanitise for use as a Rust ident.
    for set in &subs.sets {
        let ident = sanitise_ident(&set.package);
        code.push_str(&format!(
            "static SUBFEATURES_{ident}: &[&str] = &["
        ));
        for name in &set.names {
            code.push_str(&format!("{name:?}, "));
        }
        code.push_str("];\n");
    }
    code.push('\n');

    code.push_str("pub static PACKAGES: [BrowserPackage; PACKAGE_COUNT] = [\n");
    for entry in &catalog.browser {
        let subs_ref = match subs.sets.iter().find(|s| s.package == entry.package) {
            Some(s) => format!("SUBFEATURES_{}", sanitise_ident(&s.package)),
            None => "&[]".to_string(),
        };
        code.push_str(&format!(
            "    BrowserPackage {{ name: {:?}, subfeatures: {subs_ref} }},\n",
            entry.package
        ));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("catalog.rs"), code).unwrap();
}

fn sanitise_ident(package: &str) -> String {
    package
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_uppercase()
}
