[package]
name        = "feature-creature-detector"
version     = "0.1.0"
edition.workspace     = true
license.workspace     = true
repository.workspace  = true

[lib]
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]
wat  = "1.243"
toml = { version = "0.9", default-features = false, features = ["parse", "serde"] }
serde = { version = "1", features = ["derive"] }
